services:
  mdm_service:
    class: Radmas\MDMBundle\Services\MDMService
    arguments: ["%signcert%", "%privkey%", "%privkey_pass_file%", "@jms_serializer"]
    calls:
      - [setRouter, ['@router']]

