security:
    providers:
        in_memory:
            memory:
                users:
                    apple:
                        password: apple
                        roles: 'ROLE_USER'

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/enroll, roles: ROLE_USER }
